theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
cursorline  = true
color-modes = true
true-color  = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left  = [ "mode", "file-name" ]
right = [ "file-type", "position", "diagnostics", "spinner" ]

[editor.lsp]
enable                    = true
display-messages          = true
display-progress-messages = true

[editor.file-picker]
hidden          = false
git-ignore      = true
follow-symlinks = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.auto-save]
focus-lost          = true
after-delay.enable  = true
after-delay.timeout = 30000

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.normal]
";" = "insert_mode"
"h" = "no_op"
"i" = "move_line_up"
"j" = "move_char_left"
"k" = "move_line_down"
"l" = "move_char_right"

up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"

[keys.insert]
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"

[keys.select]
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"
