[packages]
brew = [
	"stikypiston/formulae/constitution",
	"stikypiston/formulae/dotkeeper",
	"stikypiston/formulae/bobafm",
	"stikypiston/formulae/chess-tui",
	"stikypiston/formulae/dotkeeper-tui",
	"stikypiston/formulae/fastcards",
	"stikypiston/formulae/hocusfocus",
	"stikypiston/formulae/pricetag",
	"stikypiston/formulae/recall",
	"bob",
	"fzf",
	"fd",
	"croc",
	"gum",
	"soft-serve",
	"zoxide",
	"eza",
	"aerc",
	"yazi",
	"swift",
	"pkl",
	"pkl-lsp",
	"gh",
	"tlrc",
	"delta",
	"lazygit",
	"stockfish",
	"ncdu",
	"zinit",
	"utftex",
	"amfora",
	"w3m",
	"luarocks",
	"ripgrep",
	"yarn",
	"helix",
	"starship",
	"tree",
	"btop",
	"ruby",
	"rustup",
	"wezterm/wezterm-linuxbrew/wezterm",
	"bat",
]
deb = [
	"zsh",
	"mangohud",
	"sassc",
	"figlet",
	"lolcat",
	"tmux",
	"libfuse2"
]
