[packages]
brew = [
	"bob",
	"stikypiston/formulae/dotkeeper",
	"stikypiston/formulae/dotkeeper-tui",
	"stikypiston/formulae/constitution",
	"stikypiston/formulae/recall",
	"gum",
	"yazi",
	"pkl",
	"swift",
	"pkl-lsp",
	"croc",
	"tlrc",
	"lazygit",
	"delta",
	"amfora",
	"zinit",
	"tree-sitter-cli",
	"fzf",
	"ripgrep",
	"bat"
]

pacman = [
	"niri",
	"waybar",
	"fuzzel",
	"nemo",
	"swww",
	"swaylock",
	"sassc",
	"alacritty",
	"wezterm",
	"fastfetch",
	"papirus-icon-theme",
	"nwg-look",
	"rhythmbox",
	"swaync",
	"nemo-share",
	"nemo-preview",
	"nemo-emblems",
	"nemo-audio-tab",
	"nemo-fileroller",
	"python3",
	"uv",
	"grim",
	"slurp",
	"less",
	"man",
	"figlet",
	"loupe",
	"zsh",
	"starship",
	"uwsm",
	"rmpc",
	"mpd",
	"zathura",
	"rustup",
	"ly",
	"tmux"
]

aur = [
	"vicinae-bin",
	"waybar-updates",
	"wlogout",
	"alertify",
	"blesh",
	"way-edges-git"
]
